notifications:
  email: false

language: node_js
node_js:
  - "11.10.1"

cache:
  directories:
    - 'node_modules'

before_install:
  - npm -g install npm@latest

script:
    - npm run test
    - npm run prettier:check

after_success:
  - chmod +x ./scripts/publish_on_netlify.sh
  - ./scripts/publish_on_netlify.sh
